<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Ejercicio 5</title>
</head>

<body>
    <table border="1">
        <tr>
            <td>Contenido de $var</td>
            <td>isset($var)</td>
            <td>empty($var)</td>
            <td>(bool)$var</td>
        </tr>
        <tr>

            <td>$var=null;</td>
            <td>
                <?php
                    $var=null;
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var=null;
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var=null;
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>$var=0;</td>
            <td>
                <?php
                    $var=0;
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var=0;
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var=0;
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>$var=true;</td>
            <td>
                <?php
                    $var=true;
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var=true;
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var=true;
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>$var=false;</td>
            <td>
                <?php
                    $var=false;
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var=false;
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var=false;
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>$var="0";</td>
            <td>
                <?php
                    $var="0";
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var="0";
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var="0";
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>$var="";</td>
            <td>
                <?php
                    $var="";
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var="";
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var="";
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>$var="foo";</td>
            <td>
                <?php
                    $var="foo";
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var="foo";
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var="foo";
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>$var=array();</td>
            <td>
                <?php
                    $var=array();
                    echo(isset($var));
                ?>
            </td>
            <td>
                <?php
                    $var=array();
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    $var=array();
                    echo((bool)$var);
                ?>
            </td>
        </tr>
        <tr>
            <td>unset($var);</td>
            <td>
                <?php
                    unset($var);
                    echo((bool)$var);
                ?>
            </td>
            <td>
                <?php
                    unset($var);
                    echo(empty($var));
                ?>
            </td>
            <td>
                <?php
                    unset($var);
                    echo((bool)$var);
                ?>
            </td>
        </tr>

    </table>

</body>

</html>
